### ISSUE TITLE
Question 1 Part A format issue

### ISSUE THREAD

**Issue by thebowenfeng** [Vaida12345/COMP30026-2023-Practise-Exam#1]
![image](https://github.com/Vaida12345/COMP30026-2023-Practise-Exam/assets/31093400/53eca276-a4b2-461b-8574-44f87e3df736)
I believe part A is asking for a single propositional formula that satisfy all 4 conditions, as opposed to 4 propositional formulas.

**Comment by Lanthian** [comment]
Agreed, yeah. See https://edstem.org/au/courses/12631/discussion/1697140?comment=3786256

**Comment by Vaida12345** [comment]
I see, thank you!
