### ISSUE TITLE
Question 4 Minor notes

### ISSUE THREAD

**Issue by Lanthian** [Vaida12345/COMP30026-2023-Practise-Exam#2]
Howdy Weida

I think in Q4 Part A the line 
> _The string is basically any number of ab followed by any number of ab._

Should actually read
> _The string is basically any number of ab followed by any number of **ba**._

And additionally (not necessary) the `ab` loop in Q4 Part B can be simplified to the below, cutting out one of the states
![image](https://github.com/Vaida12345/COMP30026-2023-Practise-Exam/assets/127370027/02b03353-5e80-4b3b-a05b-361d965c9f8d)

**Comment by Vaida12345** [comment]
You're right! That was a typo. Thank you!
